#!/usr/bin/env node
// git passes: $1=previous HEAD $2=new HEAD $3="1" for a branch checkout, "0" for a single-file checkout
import { syncImages } from './lib/sync-images.mjs';

const isBranchCheckout = process.argv[4] === '1';
if (isBranchCheckout) {
  await syncImages();
}
